### ISSUE TITLE
Mesclando página de login e página de menu das branches develop-v1 e frontend-pages

### ISSUE THREAD

**Issue by Beatriz-ge** [unb-mds/MDS-MonitoraBSB#29]
# Descrição do Problema
As páginas de **login** e **menu** estão atualmente separadas em duas branches diferentes: `develop-v1` e `frontend-pages`. Para consolidar a base de código, é necessário mesclar as mudanças dessas branches, garantindo que a funcionalidade de login e menu estejam integradas e funcionando corretamente no projeto.

# Solução Proposta
- Realizar a mesclagem das duas branches, integrando os códigos das páginas de **login** e **menu** em uma única branch.
- Resolver qualquer conflito de código entre as duas branches.
- Garantir que a navegação entre as páginas de login e menu esteja funcionando corretamente, com fluxo de usuário adequado.
- Validar que todos os elementos visuais e interativos de ambas as páginas (login e menu) estejam funcionando conforme o esperado, e que o layout seja consistente.

# Tarefas
- [ ] Realizar a mesclagem das branches `develop-v1` e `frontend-pages`.
- [ ] Resolver conflitos de código e ajustar o código de ambas as páginas.
- [ ] Garantir que o fluxo de navegação entre as páginas de login e menu esteja correto.
- [ ] Testar todas as funcionalidades de login e menu para garantir que estão operando de acordo com o esperado.
- [ ] Realizar ajustes de layout, caso necessário, para que as páginas mantenham consistência visual após a mesclagem.
- [ ] Testar a integridade do código e verificar que não há problemas de estilo ou funcionalidade nas duas páginas.

# Critérios de Aceitação
- [ ] A mesclagem das branches deve ser feita sem erros ou conflitos não resolvidos.
- [ ] O fluxo de navegação entre a página de login e a página de menu deve funcionar sem problemas.
- [ ] A página de login deve manter sua funcionalidade (como validação de campos e autenticação).
- [ ] A página de menu deve ser funcional, com todos os links e botões operando corretamente.
- [ ] O layout de ambas as páginas deve estar consistente com o design original após a mesclagem.
- [ ] Todos os testes de funcionalidade e usabilidade devem ser realizados e aprovados.

# Recursos
- Branches `develop-v1` e `frontend-pages`  
- Protótipos de design ou layouts de login e menu  
- Ferramentas de teste (como Postman, Chrome DevTools, etc.)  
- Documentação de navegação e fluxo do sistema

**Comment by jjyutm4532** [comment]
Hello, I tried to solve the issue.

This is what I did:

Added login form with username and password fields, styled consistently with the Register page, and included navigation to the register page.

You can review changes in this commit: https://github.com/jjyutm4532/unb-mds-MDS-MonitoraBSB-29/commit/ece70173745b1d3d85f8940fb9d8c4364452e505.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
